### PR TITLE
User list frontend

### PR DESCRIPTION
**Pull request by lislis**
Current state:
screen shot 2016-12-05 at 21 27 28

The maps controller lists all users. Those can be replaces by more sophisticated lists (unique letters of the alphabet in one, starting a new section with the new letter in the other)

### CODE REVIEW

**Comment by lislis** [comment]
I updated the user list on maps#show and user#show. Looks like this:
screen shot 2016-12-25 at 23 30 50
screen shot 2016-12-25 at 23 31 00
screen shot 2016-12-25 at 23 31 13

**Comment by 1000miles** [comment]
@lislis Can you please help us? We need your input on what the final intention of the sliding class elements `.list-alphabet` and `.slam-profile` is.

**Questions:**
- When clicking on the class `.l-alphabet` the `.list-alphabet` element slides to right while the `slam-profile` element is on the left, so we are wondering if it should be the other round, means left `.list-alphabet` then `.slam-profile`, or?
- Should the `list-alphabet` vanish when the `.slam-profile` appears? If yes, is the idea to move the `.slam-profile` to the position of `.list-alphabet` as a replacement? If not, wouldn't it be better to keep the `.list-alphabet` visible?

### Some Screen Examples:






with modified styles:

**.list-alphabet**
```css
  .has-js .list-alphabet {
    transform: translateX(0%); }
    .has-js .list-alphabet.is-hidden {
      transform: translateX(0%);
      z-index: -1; }
```

**.slam-profile**
```css
  .has-js .slam-profile {
    transform: translateX(100%);
  }
    .has-js .slam-profile.is-hidden {
      transform: translateX(-150%);
      z-index: -1; }
```

**Comment by lislis** [comment]
Hey there!
I hope I can make the thing clearer. Though there is still the caveat that I assumed most of the interaction as the design did not mention any of it. so it might be that everything I write and say might be wrong :D 

From what you describe it looks like the sliding might not function properly for you? In any case here is what should happen. I also recorded a video (it's a zipped webm, just drag the video file in your browser)
[slamalphas.webmhd.webm.zip](https://github.com/rubymonsters/slam-alphas/files/735739/slamalphas.webmhd.webm.zip)

`.list-alphabet` is never shown on a page load. `.l-alphabet` is there to toggle `.list-alphabet

`. This is the basic slammer to slammer navigation that the app offers. Once there are more people in the database you can jump directly to the names in question.

If you're on user#show and click the alphabetical list (`.l-alphabet`) the list list of all slammers appears and overlays the the current `.slam-profile`. The assumption is that a user would want to look for another slammer which they then could find in the appearing `.list-alphabet`. If they decide to not want that and close the `.list-alphabet` the `.slam-profile` information would still be there.

**Comment by joecorcoran** [comment]
@lislis Thanks for the helpful description and video! Turns out this was a Firefox issue and everything looks good in Chrome. @aydamacink and @eine-sandra are debugging now...

**Pull request merged**
